{
 "title": "Temperature Pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:stream_metrics_poll_rate"
    },
    {
     "expr": "application:stream_metrics_commit_rate"
    },
    {
     "expr": "application:stream_metrics_process_rate"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application:stream_metrics_commit_latency_avg"
    },
    {
     "expr": "application:stream_metrics_poll_latency_avg"
    },
    {
     "expr": "application:stream_metrics_process_latency_avg"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application:stream_metrics_process_total"
    }
   ]
  }
 ]
}